language: java

jdk:
  - openjdk8

cache:
  directories:
    - ~/.m2/repository

env:
  global:
  # GH_TOKEN
  - secure: "PRxZj10Zi8Fo8yTs61nZL5XyEv2kVjaNOHawz3RiPqaXcLLcJgkD+6r8BJujNJfSRcNpI+6v6xjR284jBtyWyaz2Givwv5xxZ2ezB0J7kb1x4+ZpTizkCCsvn+cdcCXhwec6jU879gjqF+rVzk7OmMIcCf7tt0V7s3Wsj09Ft9s="
  # SONATYPE_USER
  - secure: "axonSXozZztwlwbpJdBGrx/vI3c3v9JG4Gz0KlKSn9iOpBqgX/gNWCyr18k1SG+4TEgXzD72/6ZDDnCPSYXZv5h+SKSmCkMmboxUE0KFR1hO1SOIzJtfMpv1qfIcE0ernuZIs0BuZRh35xTYjH+N7XC9HEs0LNRPjfkduiJittA="
  # SONATYPE_PASS
  - secure: "YMeNJYBhXcLJHepHzz8r0UlhZQBK33nBMQi6plaZjt/3qnJtAxVLuu6cwuycqAyuJq6vDNe+ThAVi5MZ3jNx+tpyq2x0cET6yFAUWE+9ZiI91rJFzVmY05K8zxCnMWPGmbunl/UGPGDKk0suLQxGmlrvBgRcSVONU3KuGq7lyDc="
  # GPG_KEYNAME
  - secure: "N1TK5gAnL8WWWflDSNrwghfwaN/FjqyO1DX7vCwg5sl3DpAT70E6Ju9PJ1+FXb7wF95xMzSiHVk5haOR1FxIEX2l8aP//xHtpRcAz+RM143nDs6EhmMqmD9KlimLcApkjPupn4mx8e4BFOTGqkvK7eBoIm8jWt3zKXnz4Gwy1Ko="
  # GPG_PASSPHRASE
  - secure: "gRUj21Z0K8gOGrHXj2WuH4bww3XcRZk1iScRbVdQhhTw8SFlcVhOpXoUiM68YYZABeGNJJ9XxP8QBoKKEKV5rkxAUG5+huPTdu4bwbQgHoz71awuWsrSVWXodzbT+lBxYjXkKD/AckM69olV9ZYZ5IgsFAka3geA2tPjLCO3YjE="

after_success:
  - bash ./src/build/publish-jar.sh
  - bash ./src/build/publish-doc-snapshot.sh
  - bash ./src/build/publish-doc-release.sh
